version: '2'
services:
  postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - airflow_network

  redis:
    image: bitnami/redis:latest
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - airflow_network

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    depends_on:
      - postgresql
      - redis
    environment:
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bitnami_airflow
      - POSTGRES_USER=bn_airflow
      - POSTGRES_PASSWORD=bitnami1
    volumes:
      - '/Users/isaac/Desktop/dags:/opt/bitnami/airflow/dags'
      - 'airflow_logs:/opt/bitnami/airflow/logs'
      - '/Users/isaac/Desktop/dags/requirements.txt:/bitnami/python/requirements.txt'
    networks:
      - airflow_network
    command: >
      bash -c "pip install -r /bitnami/python/requirements.txt && airflow db init && airflow scheduler"

  airflow-worker:
    image: bitnami/airflow-worker:latest
    depends_on:
      - postgresql
      - redis
    environment:
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bitnami_airflow
      - POSTGRES_USER=bn_airflow
      - POSTGRES_PASSWORD=bitnami1
    volumes:
      - '/Users/isaac/Desktop/dags:/opt/bitnami/airflow/dags'
      - 'airflow_logs:/opt/bitnami/airflow/logs'
      - '/Users/isaac/Desktop/dags/requirements.txt:/bitnami/python/requirements.txt'
    networks:
      - airflow_network
    command: >
      bash -c "pip install -r /bitnami/python/requirements.txt && airflow celery worker"

  airflow:
    image: bitnami/airflow:latest
    depends_on:
      - postgresql
      - redis
    environment:
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=bitnami
      - AIRFLOW_USERNAME=user
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bitnami_airflow
      - POSTGRES_USER=bn_airflow
      - POSTGRES_PASSWORD=bitnami1
    ports:
      - '8080:8080'
    volumes:
      - '/Users/isaac/Desktop/dags:/opt/bitnami/airflow/dags'
      - 'airflow_logs:/opt/bitnami/airflow/logs'
      - '/Users/isaac/Desktop/dags/requirements.txt:/bitnami/python/requirements.txt'
    networks:
      - airflow_network
    command: >
      bash -c "pip install -r /bitnami/python/requirements.txt && airflow db init && airflow webserver"

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  airflow_logs:
    driver: local

networks:
  airflow_network:
    driver: bridge